<a href="https://colab.research.google.com/github/GroupQ-Assignment-DataScience/GroupQ_Assignment_RMD/blob/main/GroupQ.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
# Import Required Libraries
import pandas as pd
import numpy as np

# Visualization
import matplotlib.pyplot as plt
import seaborn as sns

# Machine Learning
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

In [4]:
import pandas as pd
df = pd.read_csv('/content/dataset_C_training.csv')

In [5]:
df.head()

,respondent_id,covid_concern,covid_knowledge,behavioral_antiviral_meds,behavioral_avoidance,behavioral_face_mask,behavioral_wash_hands,behavioral_large_gatherings,behavioral_outside_home,behavioral_touch_face,...,employment_status,census_msa,household_adults,household_children,doctor_recc_covid,opinion_covid_vacc_effective,opinion_covid_risk,opinion_covid_sick_from_vacc,employment_sector,covid_vaccine
0,1,3.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,1.0,...,Employed,"MSA, Principle City",3.0,2.0,0,4,4,2.0,construction,0
1,2,2.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,...,Employed,Non-MSA,0.0,0.0,0,5,2,1.0,education,1
2,3,0.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,Employed,"MSA, Not Principle City",0.0,0.0,0,2,2,5.0,wholesale,0
3,4,2.0,2.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,...,Not in Labor Force,"MSA, Not Principle City",1.0,0.0,1,3,3,2.0,NaN,1
4,5,1.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,Employed,"MSA, Not Principle City",0.0,0.0,0,3,2,2.0,wholesale,0

In [6]:
# Basic Dataset Information
print("Shape of Dataset:", df.shape)

df.info()

Shape of Dataset: (4756, 31)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4756 entries, 0 to 4755
Data columns (total 31 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   respondent_id                 4756 non-null   int64
 1   covid_concern                 4744 non-null   float64
 2   covid_knowledge               4729 non-null   float64
 3   behavioral_antiviral_meds     4742 non-null   float64
 4   behavioral_avoidance          4729 non-null   float64
 5   behavioral_face_mask          4754 non-null   float64
 6   behavioral_wash_hands         4747 non-null   float64
 7   behavioral_large_gatherings   4746 non-null   float64
 8   behavioral_outside_home       4742 non-null   float64
 9   behavioral_touch_face         4735 non-null   float64
 10  chronic_med_condition         4587 non-null   float64
 11  child_under_6_months          4621 non-null   float64
 12  health_worker                 4624 non-null   float64
 13  health_insurance              2848 non-null   float64
 14  age_group                     4756 non-null   object
 15  education                     4528 non-null   object
 16  race                          4756 non-null   object
 17  sex                           4756 non-null   object
 18  income_poverty                4008 non-null   object
 19  marital_status                4525 non-null   object
 20  rent_or_own                   4427 non-null   object
 21  employment_status             4518 non-null   object
 22  census_msa                    4756 non-null   object
 23  household_adults              4717 non-null   float64
 24  household_children            4717 non-null   float64
 25  doctor_recc_covid             4756 non-null   int64
 26  opinion_covid_vacc_effective  4756 non-null   int64
 27  opinion_covid_risk            4756 non-null   int64
 28  opinion_covid_sick_from_vacc  4666 non-null   float64
 29  employment_sector             2426 non-null   object
 30  covid_vaccine                 4756 non-null   int64
dtypes: float64(16), int64(5), object(10)
memory usage: 1.1+ MB

In [7]:
# ==========================================
# STEP 4: Check Missing Values
# ==========================================

missing_values = df.isnull().sum()

# Show columns with missing values
missing_values[missing_values > 0].sort_values(ascending=False)

employment_sector               2330
health_insurance                1908
income_poverty                   748
rent_or_own                      329
employment_status                238
marital_status                   231
education                        228
chronic_med_condition            169
child_under_6_months             135
health_worker                    132
opinion_covid_sick_from_vacc      90
household_children                39
household_adults                  39
covid_knowledge                   27
behavioral_avoidance              27
behavioral_touch_face             21
behavioral_outside_home           14
behavioral_antiviral_meds         14
covid_concern                     12
behavioral_large_gatherings       10
behavioral_wash_hands              9
behavioral_face_mask               2
dtype: int64

In [8]:
# ==========================================
# STEP 5: Calculate Missing Value Percentage
# ==========================================

missing_percent = (df.isnull().sum() / len(df)) * 100

missing_report = pd.DataFrame({
    'Missing Values': df.isnull().sum(),
    'Percentage': missing_percent
})

missing_report[missing_report['Missing Values'] > 0]\
.sort_values(by='Percentage', ascending=False)

                              Missing Values  Percentage
employment_sector                       2330   48.990749
health_insurance                        1908   40.117746
income_poverty                           748   15.727502
rent_or_own                              329    6.917578
employment_status                        238    5.004205
marital_status                           231    4.857023
education                                228    4.793944
chronic_med_condition                    169    3.553406
child_under_6_months                     135    2.838520
health_worker                            132    2.775442
opinion_covid_sick_from_vacc              90    1.892347
household_children                        39    0.820017
household_adults                          39    0.820017
covid_knowledge                           27    0.567704
behavioral_avoidance                      27    0.567704
behavioral_touch_face                     21    0.441548
behavioral_outside_home                   14    0.294365
behavioral_antiviral_meds                 14    0.294365
covid_concern                             12    0.252313
behavioral_large_gatherings               10    0.210261
behavioral_wash_hands                      9    0.189235
behavioral_face_mask                       2    0.042052

In [9]:
# Separate categorical and numerical columns

categorical_columns = df.select_dtypes(include='object').columns
numerical_columns = df.select_dtypes(exclude='object').columns

# Fill categorical missing values
for col in categorical_columns:
    df[col] = df[col].fillna("Unknown")

# Fill numerical missing values
for col in numerical_columns:
    df[col] = df[col].fillna(df[col].median())

In [11]:
# Check remaining missing values

print("Remaining Missing Values:")
print(df.isnull().sum().sum())

Remaining Missing Values:
0

In [12]:
# Convert categorical variables into numerical format

label_encoder = LabelEncoder()

for col in categorical_columns:
    df[col] = label_encoder.fit_transform(df[col])

df.head()

,respondent_id,covid_concern,covid_knowledge,behavioral_antiviral_meds,behavioral_avoidance,behavioral_face_mask,behavioral_wash_hands,behavioral_large_gatherings,behavioral_outside_home,behavioral_touch_face,...,employment_status,census_msa,household_adults,household_children,doctor_recc_covid,opinion_covid_vacc_effective,opinion_covid_risk,opinion_covid_sick_from_vacc,employment_sector,covid_vaccine
0,1,3.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,1.0,...,0,1,3.0,2.0,0,4,4,2.0,3,0
1,2,2.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,...,0,2,0.0,0.0,0,5,2,1.0,4,1
2,3,0.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0.0,0.0,0,2,2,5.0,21,0
3,4,2.0,2.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,...,1,0,1.0,0.0,1,3,3,2.0,0,1
4,5,1.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0.0,0.0,0,3,2,2.0,21,0